# -*- coding: utf-8 -*-
"""Stroke_Risk_Analysis ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKEaFQ4HZeUWotQBY0fjwJQK_RxlDoIZ

### What factors are most related to stroke risk in patients?

Load, explore, clean data
"""

#load necesarry libraries
import pandas as pd
from scipy.stats import ttest_ind
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/healthcare-dataset-stroke-data.xls')
df.head()

#explore data

df.info()
df.describe()

#clean data

df = df.dropna()

"""### Analyze Relationships"""

# find differences between stroke and non stroke patients

stroke_patients = df[df['stroke'] == 1 ]
non_stroke_patients = df[df['stroke'] == 0 ]

#compare average age

print("Average age (stroke):", stroke_patients['age'].mean())

print("Average age (no stroke):", non_stroke_patients['age'].mean())

#compare stroke rates for hypertension

print("Hypertension rate (stroke ):", stroke_patients['hypertension'].mean())

#compare stroke rates for smokers

df.groupby('smoking_status')["stroke"].mean()

#BMI Categorization
df['bmi_category'] = pd.cut(df['bmi'],
                             bins=[0, 18.5, 24.9, 29.9, float('inf')],
                             labels=['Underweight', 'Normal weight', 'Overweight', 'Obese'])

#glucose level categorization
df['glucose_category'] = pd.cut(df['avg_glucose_level'],
                                 bins=[0, 100, 125, float('inf')],
                                 labels=['Normal', 'Prediabetic', 'Diabetic'])

"""T-test for BMI by Stroke in Each BMI Category

"""

# Check how many underweight patients had stroke vs. no stroke
underweight = df[df['bmi_category'] == 'Underweight']

# Count how many had stroke (stroke == 1) and how many didn't (stroke == 0)
print("Underweight stroke count:", underweight[underweight['stroke'] == 1].shape[0])
print("Underweight no stroke count:", underweight[underweight['stroke'] == 0].shape[0])


# Get unique BMI categories
categories = df['bmi_category'].unique()

# Loop through each category and run a t-test
for category in categories:
    group = df[df['bmi_category'] == category]

    stroke = group[group['stroke'] == 1]['bmi'].dropna()
    no_stroke = group[group['stroke'] == 0]['bmi'].dropna()

    t_stat, p_val = ttest_ind(stroke, no_stroke, equal_var=False)  # Welch's t-test

    print(f"{category} — t-statistic: {t_stat:.3f}, p-value: {p_val:.4f}")

"""Create Graphs"""

df.groupby('hypertension')['stroke'].mean().plot(kind='bar')
plt.title("Stroke Rate by Hypertension Status")
plt.ylabel("Stroke Rate")
plt.xlabel("Hypertension (0 = NO, Y = YES) ")
plt.show()

df['age_group'] = pd.cut(df['age'], bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
df.groupby('age_group')['stroke'].mean().plot(kind='bar')
plt.title("Stroke Rate by Age Group")
plt.ylabel("Stroke Rate")
plt.xlabel("Age Group")
plt.show()

df.groupby('gender')['stroke'].mean().plot(kind='bar')
plt.title("Stroke Rate by Gender")
plt.ylabel("Stroke Rate")
plt.xlabel("Gender")
plt.show()

df.groupby('smoking_status')['stroke'].mean().plot(kind='bar')
plt.title("Stroke Rate by Smoking Status")
plt.ylabel("Stroke Rate")
plt.xlabel("Smoking Status")
plt.show()

df.groupby('glucose_category')['stroke'].mean().plot(kind='bar')
plt.title("Stroke Rate by Glucose Level Category")
plt.ylabel("Stroke Rate")
plt.xlabel("Glucose Level Category")
plt.show()

sns.boxplot(x='stroke', y='bmi', hue='bmi_category', data=df)
plt.title("BMI Distribution by Stroke and BMI Category")
plt.xlabel("Stroke")
plt.ylabel("BMI")
plt.show()

"""### Summary

Stroke Risk Analysis

I analyzed a heatlhcare dataset with 5,000 patient records to identify factor associated with stroke risk.

1. Stroke Rate by Age Group:
The graph shows that stroke risk significantly increases with age. The stroke rate is considerably higher in the older age groups 60+. This aligns with general medical knowledge that stroke risk increases with age.

2. Stroke Rate by Gender:

Based on the graph, I observd a slightly higher stroke rate in males.


3. Stroke Rate by Smoking Status:

In this graph you can see that "formerly smoked" and "smokes" categories have higher stroke rates compared to "never smoked". This strongly suggests that smoking, both current and past, is a significant risk factor for stroke.


4. Relationship between Age and Average Glucose Level for Stroke and Non-stroke Patients:


The scatter plot of Age vs. Average Glucose Level showed a higher concentration of stroke cases at older ages and higher glucose levels, suggesting a positive correlation.
By categorizing glucose levels, we can further refine this finding. The bar chart of Stroke Rate by Glucose Level Category reveals that:
Stroke risk increases with increasing glucose levels.
Individuals in the "Diabetic" category have the highest stroke rate.
This confirms that higher glucose levels, particularly in the diabetic range, significantly increase the likelihood of stroke.



5. Relationship between BMI and Heart Disease for Stroke and Non-stroke Patients:


This boxplot shows how BMI is spread out across people who have had a stroke and those who haven’t, broken down by BMI category (Underweight, Normal weight, Overweight, Obese).


People in the obese group have the highest BMIs overall, and there are a lot of outliers — especially in the group that didn’t have a stroke. So even though they're all considered obese, some have way higher BMIs than others.

For those who did have a stroke, the median BMI in the obese category looks a little higher, which might suggest a connection but it’s not a huge difference.

Underweight people have low BMIs with barely any spread, and that doesn’t change much whether they had a stroke or not.

The normal and overweight groups look pretty similar for both stroke and no-stroke. Not a lot of change in medians or spread.

BMI, broken down by category, didn’t show a strong link on its own:

I ran an independent t-tests comparing BMI values between stroke and non-stroke groups within each BMI category.

None of the p-values were below 0.05, so BMI differences between stroke and non-stroke groups were not statistically significant in any category.

For example:

Obese: p = 0.1057

Normal weight: p = 0.0909

Overweight: p = 0.4543

Underweight: Not enough data to test


Overall Summary:



Age is a strong risk factor for stroke, with risk increasing significantly in older age groups.

Smoking, both current and past, increases stroke risk.

Higher glucose levels are associated with a greater likelihood of stroke, especially in older individuals.

Higher BMI is a potential risk factor for stroke, and heart disease might further increase this risk.

Based on my analysis, age and hypertension appear to be the most related to stroke risk in this dataset. While BMI is often considered in health outcomes, it didn’t show a statistically significant relationship to stroke on its own here.
"""